# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenConversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversationTopic', models.CharField(max_length=200)),
                ('maxPeople', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('race', models.CharField(max_length=255)),
                ('sexuality', models.CharField(max_length=8)),
                ('roast', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='firstTest.Person'),
        ),
        migrations.AddField(
            model_name='people',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person1', to='firstTest.Person'),
        ),
        migrations.AddField(
            model_name='people',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person2', to='firstTest.Person'),
        ),
        migrations.AddField(
            model_name='people',
            name='person3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person3', to='firstTest.Person'),
        ),
        migrations.AddField(
            model_name='people',
            name='person4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person4', to='firstTest.Person'),
        ),
        migrations.AddField(
            model_name='openconversations',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstTest.People'),
        ),
    ]
