# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openconversations',
            name='peoplePresent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openconversations',
            name='people',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstTest.People'),
        ),
        migrations.AlterField(
            model_name='people',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='firstTest.Person'),
        ),
        migrations.AlterField(
            model_name='people',
            name='person1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person1', to='firstTest.Person'),
        ),
        migrations.AlterField(
            model_name='people',
            name='person2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person2', to='firstTest.Person'),
        ),
        migrations.AlterField(
            model_name='people',
            name='person3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person3', to='firstTest.Person'),
        ),
        migrations.AlterField(
            model_name='people',
            name='person4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person4', to='firstTest.Person'),
        ),
    ]
